<a href="https://colab.research.google.com/github/doddamaniaaradya/AI_CODING/blob/main/Project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import pandas as pd

pets = pd.DataFrame({
    "name": ["Bruno", "Mittens", "Nemo", "Coco", "Hopper", "Shelly"],
    "animal": ["Dog", "Cat", "Fish", "Parrot", "Rabbit", "Turtle"],
    "legs": [4, 4, 0, 2, 4, 4],
    "cuteness": [9, 10, 6, 8, 10, 7],
    "sound": ["Woof", "Meow", "Blub", "Hello!", "Squeak", "Hmm"]
})
pets

      name  animal  legs  cuteness   sound
0    Bruno     Dog     4         9    Woof
1  Mittens     Cat     4        10    Meow
2     Nemo    Fish     0         6    Blub
3     Coco  Parrot     2         8  Hello!
4   Hopper  Rabbit     4        10  Squeak
5   Shelly  Turtle     4         7     Hmm

ASK THE TABLE QUESTIONS

In [62]:
print(pets["name"])

0      Bruno
1    Mittens
2       Nemo
3       Coco
4     Hopper
5     Shelly
Name: name, dtype: object

In [63]:
print("Rows and columns:", pets.shape)

Rows and columns: (6, 5)

In [64]:
print("How many pets?", len(pets))

How many pets? 6

· Filter: find the cutest pets

In [65]:
super_cute = pets[pets["cuteness"] ==10]
super_cute

      name  animal  legs  cuteness   sound
1  Mittens     Cat     4        10    Meow
4   Hopper  Rabbit     4        10  Squeak

Filter: pets with 4 legs

In [66]:
pets[pets["legs"] == 4]

      name  animal  legs  cuteness   sound
0    Bruno     Dog     4         9    Woof
1  Mittens     Cat     4        10    Meow
4   Hopper  Rabbit     4        10  Squeak
5   Shelly  Turtle     4         7     Hmm

· Sort: the cuteness leaderboard

In [67]:
pets.sort_values("cuteness", ascending=False)

      name  animal  legs  cuteness   sound
1  Mittens     Cat     4        10    Meow
4   Hopper  Rabbit     4        10  Squeak
0    Bruno     Dog     4         9    Woof
3     Coco  Parrot     2         8  Hello!
5   Shelly  Turtle     4         7     Hmm
2     Nemo    Fish     0         6    Blub

· Add a new pet

In [68]:
pets.loc[len(pets)] = ["Sparky", "Hamster", 4, 9, "Squeak squeak"]
pets

      name   animal  legs  cuteness          sound
0    Bruno      Dog     4         9           Woof
1  Mittens      Cat     4        10           Meow
2     Nemo     Fish     0         6           Blub
3     Coco   Parrot     2         8         Hello!
4   Hopper   Rabbit     4        10         Squeak
5   Shelly   Turtle     4         7            Hmm
6   Sparky  Hamster     4         9  Squeak squeak

· Maths on a column

In [69]:
print("Average cuteness:", round(pets["cuteness"].mean(),1))

Average cuteness: 8.4

In [70]:
print("Highest cuteness:", pets["cuteness"].max())

Highest cuteness: 10

In [71]:
print("Total legs in my zoo:", pets["legs"].sum())

Total legs in my zoo: 22

Pet Detective!

In [72]:
pet = pets.sample(1).iloc[0]   # the computer secretly picks one pet
print("Clue 1: I have", pet["legs"], "legs.")
print("Clue 2: My cuteness score is", pet["cuteness"])
print("Clue 3: I say", pet["sound"])
guess = input("Which animal am I? ")
if guess.lower() == pet["animal"].lower():
  print("Correct! You are a Pet Detective!")
else: print("Oops! I was", pet["name"], "the", pet["animal"])

Clue 1: I have 4 legs.
Clue 2: My cuteness score is 10
Clue 3: I say Squeak
Which animal am I? rabbit
Correct! You are a Pet Detective!

Advanced Pet Detective!

In [60]:
score = 0

for turn in range(3):            # play 3 rounds
 pet = pets.sample(1).iloc[0]
 print("Clues:", pet["legs"], "legs,", "says", pet["sound"])
 guess = input("Which animal am I? ")
 if guess.lower() == pet["animal"].lower():
  print("Correct!")
  score = score + 1
 else: print("It was the", pet["animal"])
print("Your detective score:",score, "out of 3")

Clues: 4 legs, says Squeak
Which animal am I? rabbit
Correct!
Clues: 2 legs, says Hello!
Which animal am I? parrot
Correct!
Clues: 4 legs, says Meow
Which animal am I? cat
Correct!
Your detective score: 3 out of 3